version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app_network
    depends_on:
      - app1
      - app2

  app1:
    image: httpd:latest
    container_name: my-httpd1
    networks:
      - app_network

  app2:
    image: httpd:latest
    container_name: my-httpd2
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
